### ISSUE TITLE
What would you use for photo albums?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/PBR#1]
Hey @MattReimer, question for you on these GitHosted sites. What would you suggest using for an album? It is easy enough to dump some photos into Google Photos and create an album, but it is really difficult to have an embedded album or slideshow.  [This publicalbum.org](http://suewaters.com/2018/07/11/embed-google-photos-album-into-a-website/) seems to be a work around for embedded Google Album slide show, but none of them show a gallery of stuff. I'm wondering if you just use a ['Card'](https://riverscapes.github.io/TemplateDocs/styleguide.html#cards) to link to an album with a static cover picture, and then just leave the album all in Google Photos? The annoying part here is the html on those `  <div class="card">` are finicky...  and all the visual stuff is static (e.g. image, and any data/or info on album). 

I see there are lots of solutions for setting up your own server and doing something: 
- https://github.com/Kickball/awesome-selfhosted#photo-and-video-galleries
- https://lychee.electerious.com/

I wonder if these are over-complicated? The nice thing about Google Photos is so many people use it and it takes care of a ton of the details. 

Thoughts?

**Comment by MattReimer** [comment]
Hmm. yeah this is a tough one. I'd say you definitely don't want to self-host pictures if you can help it. Messy and tedious.

This looks promising but I haven't tried it yet.
https://www.publicalbum.org/blog/embedding-google-photos-albums

The embed code it gives you is a 3rd party javascript library but I'm not seeing any red flags. Basically it just dumps all the images from the album and uses its own javascript to play them. Not very elegant and it won't update automatically if you add more photos later. 

That might get you over the hump but we might be able to use part of the embed code from this tool with Foundation's own carousel library to get thing looking a little nicer.

**Comment by joewheaton** [comment]
Worked well. Thanks Matt.
