### ISSUE TITLE
Punchlist of Syllabus Errors to Fix

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/PBR#17]
## [WATS 5620](http://lowtechpbr.restoration.usu.edu/workshops/2021/USU/WATS-5620/)
- [x] Read Through and find anything that doesn't make sense.
- [x] Fix dates to correct meeting time and date (check in Banner and make consistent with Canvas)

## [WATS 5624](http://lowtechpbr.restoration.usu.edu/workshops/2021/USU/WATS-5624/)
- [x] Read Through and find anything that doesn't make sense.
- [x] Fix dates to correct meeting time and date (check in Banner and make consistent with Canvas)

**Comment by mikeclawson** [comment]
Links to the PDFs of both the design manual and pocket guide are bad on both these course pages as well as other places in the website.  Not sure if it is a problem with the host site or if we have a bad url.
