### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/PBR#3]
Hey @MattReimer and @philipbaileynar,
Are these something that will be fixed in the new updates to the riverscapes template? 
https://github.com/Riverscapes/PBR/network/alerts

**Comment by philipbaileynar** [comment]
Yes they will be fixed. Perhaps more important, when anything gets out of date in the future, the cause of these alerts, we will only get one copy of the alert for the central template repo. And the fix will only need to be implemented in this one place.
