### ISSUE TITLE
Commits not being rendered in git-hosted pages

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/PBR#4]
Hey @philipbaileynar 
I made 3 commits yesterday  (minor changes to some pages):
- [02d790b3825a9a610461c81f6324faedc152b055](https://github.com/Riverscapes/PBR/commit/02d790b3825a9a610461c81f6324faedc152b055)
- [858739807a36f538cb5c4f1890697f2423385dab](https://github.com/Riverscapes/PBR/commit/858739807a36f538cb5c4f1890697f2423385dab)
- & [a833bc5bb7c7c67eb3f09f756072ce7ce284f3c9](https://github.com/Riverscapes/PBR/commit/a833bc5bb7c7c67eb3f09f756072ce7ce284f3c9)

They previewed fine on a local server, but when pushed up to master on GitHub, nothing updated (i.e. the [new page](https://github.com/Riverscapes/PBR/blob/master/workshops/Materials/Intro/materials.md) does not show up at: http://lowtechpbr.restoration.usu.edu/workshops/Materials/Intro/materials and the old [deleted pages](https://github.com/Riverscapes/PBR/commit/858739807a36f538cb5c4f1890697f2423385dab) (http://lowtechpbr.restoration.usu.edu/workshops/2019/SGI/materials.html) are still showing present)? I've never had this happen... Any ideas?

**Comment by joewheaton** [comment]
So I just went to look at it on a local server in bash session and got the warning on `jekyll serve` command of:

> Incremental build: disabled. Enable with --incremental
>     Generating...
> Liquid Exception: Liquid syntax error (line 50): Variable '{{ site.baseurl }' was not properly temrinated with regexp:/}}\}/ in workshops/2019/RC/index.md
> jekyll 3.7.3

**Comment by joewheaton** [comment]
Okay... that fix of syntax error worked on local server. ...

Also got this email:

> The page build failed for the `master` branch with the following error:
> 
> The variable `{{ site.baseurl }` on line 50 in `workshops/2019/SGI/index.md` was not properly closed with `}}`. For more information, see https://help.github.com/en/articles/page-build-failed-tag-not-properly-terminated.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by joewheaton** [comment]
Yep okay, that did the trick. Sorry for false alarm...

**Comment by philipbaileynar** [comment]
Yeah... I have yet to find a situation where the GitHub build failed and it wasn't my fault... bad frontmatter or as in this case an unclosed liquid tag (squiggly braces) etc
